### ISSUE TITLE
digest

### ISSUE THREAD

**Issue by alwx2008** [Zygahedron/Starbecue#52]
Neither digest nor soft digest is dealing damage to me from the NPCs and spawnable predators.

**Comment by WasabiRaptor** [comment]
are you using the display effect option? and are you on a ship or another "safe" location?

**Comment by alwx2008** [comment]
Im on my ship with a prey enabler on it

**Comment by alwx2008** [comment]
I think it was from me having display effects checked

**Comment by alwx2008** [comment]
Its working now

**Comment by WasabiRaptor** [comment]
the display effect version uses the damage request hooks to make it display the number rather than just modifying the value directly, therefore it doesn't apply damage in "safe" worlds, you'll have to use a mod which will modify the config to make ships not safe

also, the big prey enabler lever is not from my mod and has nothing to do with my mod
