### ISSUE TITLE
Cannot be eaten bug. compatibility? maybe?

### ISSUE THREAD

**Issue by Support-Sergal** [Zygahedron/Starbecue#57]
<h1> Reproduction: </h1>
Go to any cuties that can vore you VIA dialogue

- Click "Vore me!"
- click "..."
- and have it fail to work.

<H2>Notes</H2>
The mods used are from a collection that a freind has made. i have changed it a bit to make it work with FU
(they made a garbage mod pack that has it take a minute to load the game, with it stuttering when ever collecting a new item.)
i will be removing most of my mods to "Fix" the dumbster fire that i was handed with when tasked to make it work with FU 
Anyways. have the funny ho-ha error log.. 

[starbound.log.txt](https://github.com/Zygahedron/Starbecue/files/10017972/starbound.log.txt)

**Comment by WasabiRaptor** [comment]
this log has no errors from any sbq script in this log, when did you copy this log, did you encounter the error ingame, then send that log, or did you restart the game and not reproduce the error before sending the log

**Comment by Support-Sergal** [comment]
"(AssetException) No such asset '/humanoid/sbqSandy_Fevix/voreControllerIcons/breastVore.png'
[19:06:59.318] [Error] Could not load image asset '/humanoid/avali/voreControllerIcons/oralVore.png', using placeholder default.
(AssetException) No such asset '/humanoid/avali/voreControllerIcons/oralVore.png'
[19:06:59.318] [Error] Could not load image asset '/humanoid/avali/voreControllerIcons/analVore.png', using placeholder default.
(AssetException) No such asset '/humanoid/avali/voreControllerIcons/analVore.png'
[19:07:18.751] [Error] Could not load audio asset '/sfx/objects/gulp.ogg', using placeholder default."

Those are the only errors i got. that keeped on repeating once i clicked the "Vore Me!" Button.

**Comment by WasabiRaptor** [comment]
yeah ok, those are only errors because I can't stop them from printing to the log when they're not actually an error because they're getting the defaults when theres no unique graphic for the species

it is likely that some other mod you have is causing the messenger scripts to not load and therefore entities are never receiving the message to allow them to be eaten

someone had such an issue with a mod called `memento mori`

this would not just be an incompatibility with just SBQ if a mod broke loading these scripts, it would cause problems with any mod that loaded after it that uses messenger scripts

**Comment by Support-Sergal** [comment]
ah. let me go check if I have that and ill come back to yu.

**Comment by Support-Sergal** [comment]
yep!
![yes](https://user-images.githubusercontent.com/83624306/202364866-ad38ffa4-b388-42f4-897d-1194af23945f.png)

welp, when you get around to making an incompatible list you now know.
